FROM node:14 as builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:14-alpine

WORKDIR /app

COPY --from=builder /app/dist ./dist

RUN npm install -g http-server

EXPOSE 8080

CMD [ "http-server", "dist" ]
